export const Actions ={

MOVIES_LOADING:'MOVİES_LOADING',
MOVIES_SUCCESS:'MOVİES_SUCCESS',
MOVIES_ERROR:'MOVİES_ERROR',


GENRES_LOADING:'GENRES_LOADING',
GENRES_SUCCESS:'GENRES_SUCCESS',
GENRES_ERROR:'GENRES_ERROR',


}
export default Actions;